# Generated by Django 2.1.7 on 2019-03-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='githubUser',
            fields=[
                ('userName', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('lastActivity', models.CharField(max_length=255)),
            ],
        ),
    ]
