# Generated by Django 2.1.7 on 2019-03-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customerInfo',
            new_name='Customer',
        ),
    ]
