# Generated by Django 2.1.7 on 2019-03-15 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
        ('customer', '0002_auto_20190308_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='github_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.githubUser'),
        ),
    ]
