# Generated by Django 2.1.7 on 2019-03-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_github_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='github_user',
        ),
        migrations.AddField(
            model_name='customer',
            name='activity',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='githubUserName',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
